BIRA Issue Tracker/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BIRA_Issue_Tracker.Models;
using BIRA_Issue_Tracker.Models.IssueTracker;
using Microsoft.AspNet.Identity;

namespace BIRA_Issue_Tracker.Controllers
{
	public class HomeController : Controller
	{
		public ActionResult Index()
		{
			var db = new IssueTrackerDbContext();

			if (User.Identity.IsAuthenticated)
			{
				var unresolvedIssues = db.Issues.Where(a => a.State != State.Closed && a.State != State.Fixed);
				ViewBag.UnresolvedIssuesCount = unresolvedIssues.Count();

				var currentUser = db.Users.Find(User.Identity.GetUserId());
				ViewBag.Username = currentUser.FullName.Split(' ')[0];
				ViewBag.UserAssignedUnresolvedIssuesCount = unresolvedIssues.Count(a => a.Assignee.Id == currentUser.Id);
			}

			return View();
		}

		public ActionResult About()
		{
			ViewBag.Message = "Your application description page.";

			return View();
		}

		public ActionResult Contact()
		{
			ViewBag.Message = "Your contact page.";

			return View();
		}
	}
}

BIRA Issue Tracker/Controllers/TagsController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using BIRA_Issue_Tracker.Models;
using BIRA_Issue_Tracker.Models.IssueTracker;

namespace BIRA_Issue_Tracker.Controllers
{
	public class TagsController : Controller
	{
		private IssueTrackerDbContext db = new IssueTrackerDbContext();

		// GET: Tags
		public ActionResult Index()
		{
			return View(db.Tags.ToList());
		}

		protected override void Dispose(bool disposing)
		{
			if (disposing)
			{
				db.Dispose();
			}
			base.Dispose(disposing);
		}
	}
}

BIRA Issue Tracker/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

BIRA Issue Tracker/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

BIRA Issue Tracker/Views/Home/Index.cshtml
@{
	ViewBag.Title = Request.IsAuthenticated ? "Dashboard" : "BIRA Issue Tracker";
}

<div class="jumbotron">
	<div class="jumbo-logo center-block text-center">
		<div class="beer-and-bubbles">
			<img src="~/Images/BIRA_Logo_nobubbles.png" alt="BIRA Logo" class="img-responsive" />
			<div class="bubble1">
				<div class="bubbleReflection"></div>
			</div>
			<div class="bubble2">
				<div class="bubbleReflection"></div>
			</div>
			<div class="bubble3">
				<div class="bubbleReflection"></div>
			</div>
		</div>
	</div>

	@if (!Request.IsAuthenticated)
	{
		<blockquote class="text-center">
			<i>Everyone has issues. We just happen to track them...</i>
		</blockquote>
	}
	else
	{
		string username = ViewBag.Username;
		
		int numberOfIssues = ViewBag.UnresolvedIssuesCount;

		int userAssignedIssuesCount = ViewBag.UserAssignedUnresolvedIssuesCount;
		var userAssignedIssuesText = userAssignedIssuesCount == 0 ? "none" : $"<a href=\"/Issues/AssignedToMe\">{userAssignedIssuesCount}</a>";

		var workOrRest = userAssignedIssuesCount > 0 ? "get to work" : "take a break";
		<h3 class="text-center">Hey there @username! Time to @workOrRest!</h3>
		<h4 class="text-center"><i>There are @numberOfIssues open issues and @Html.Raw(userAssignedIssuesText) of them are assigned to you.</i></h4>
	}

	@if (!Request.IsAuthenticated)
	{
		<div class="text-center">
			<div>
				<h3>Join us now!</h3>
				<div>@Html.ActionLink("Register", "Register", "Account", null, new {@class = "btn btn-success btn-lg"})</div>
			</div>

			<div>
				<h5>Already have an account?</h5>
				<div>@Html.ActionLink("Log in", "Login", "Account", null, new {@class = "btn btn-default btn-md"})</div>
			</div>
		</div>
	}
</div>


<div class="row">
	@if (Request.IsAuthenticated)
	{
		<div class="col-md-3">
			<h2>Issues</h2>
			<p>Submit an issue</p>
			<p>
				@Html.ActionLink("Submit New", "New", "Issues", null, new {@class = "btn btn-primary"})
			</p>
		</div>
		<div class="col-md-3">
			<h2>Account</h2>
			<p>Manage your account</p>
			<p>
				@Html.ActionLink("Manage account", "Index", "Manage", null, new {@class = "btn btn-default"})
			</p>
		</div>
	}

	@{
		var columnSize = Request.IsAuthenticated ? "3" : "4";
		var offset = Request.IsAuthenticated ? string.Empty : " col-md-offset-2";
	}

	<div class="col-md-@columnSize@offset">
		<h2>All issues</h2>
		<p>
			Get acquainted with the current issues
		</p>
		<p>
			@Html.ActionLink("View All Issues", "Index", "Issues", null, new {@class = "btn btn-default"})
		</p>
	</div>
	<div class="col-md-@columnSize">
		<h2>View tags</h2>
		<p>Check out how issues are categorized.</p>
		<p>
			@Html.ActionLink("View Tags", "Index", "Tags", null, new {@class = "btn btn-default"})
		</p>
	</div>
</div>